repos:
  - repo: local
    hooks:
      - id: testslide
        name: TestSlide Suite
        entry: uv run testslide syn-pool/test_SYNAPSEware_parse_testslide.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
